services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    container_name: santa-postgres
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=santa
    ports:
      - 5432:5432
    volumes:
      - ~/.docker/data/postgres:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    restart: always
    container_name: santa-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ~/.docker/data/redis:/bitnami/redis/data
